### ISSUE TITLE
firestoreのadmin使用

### ISSUE THREAD

**Issue by EibaKatsu** [nounsjp/localnouns-frontend#15]
adminはfunctionやバッチで使うものなので、vueでは使わないほうが良いです
ERROR in src/firestore/token.ts:one:24
TS2307: Cannot find module 'firebase-admin' or its corresponding type declarations.
  > 1 | import * as admin from "firebase-admin";

**Comment by isamu** [comment]
あ、これってサーバ用の関数ですね。
であれば、server以下に置いたほうがわかりやすいですね。
server用途ならadminは使って問題ないです。

**Comment by EibaKatsu** [comment]
2ec7e98
tokenのインターフェースとfirestoreアクセスを分離しました

**Comment by EibaKatsu** [comment]
[2ec7e98](https://github.com/nounsjp/localnouns-frontend/pull/19/commits/2ec7e98a96654abc4cb34255e406a127a894cd43)
